aliases: []
creation_timestamp: 1745996295224
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1745996295224
metrics: null
model_id: ''
name: donut-base-finetuned-docvqa
params: null
run_id: 67493136efb6467290e9e387a3eeb0fd
run_link: ''
source: mlflow-artifacts:/507893471775702031/67493136efb6467290e9e387a3eeb0fd/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/507893471775702031/67493136efb6467290e9e387a3eeb0fd/artifacts/model
user_id: null
version: 4
