version: '1'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_fyp
    hostname: "grafana-fyp"
    ports:
      - "3003:3000"
    volumes:
      - "C:/navod/Academic/sem7/fyp/grafana:/var/lib/grafana"

  influxdb:
    image: influxdb
    container_name: influxdb_fyp
    hostname: "influxdb-fyp"
    ports:
      - "8086:8086"
    volumes:
      - "C:/navod/Academic/sem7/fyp/influxdb:/var/lib/influxdb2"