version: "2"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    hostname: "mlflow"
    ports:
      - "5001:5000"
    volumes:
      - "./mlflow_data:/mlruns"
    command: mlflow server --gunicorn-opts '--timeout 120' --host 0.0.0.0 --port 5000
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000

  grafana:
    image: grafana/grafana
    container_name: grafana_fyp
    hostname: "grafana-fyp"
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - "./grafana:/var/lib/grafana"

  influxdb:
    image: influxdb
    container_name: influxdb_fyp
    hostname: "influxdb-fyp"
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb:/var/lib/influxdb2"

  mysql:
    image: mysql:8.0
    container_name: mysql_fyp
    hostname: "mysql-fyp"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - "./mysql:/var/lib/mysql"
