version: '1'
services:
  influx_grafana:
    image: philhawthorne/docker-influxdb-grafana
    container_name: influx_chronograf_fyp
    hostname: "influx-chronograf-fyp"
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
    volumes:
      - "C:/navod/Academic/sem7/fyp/influxdb:/var/lib/influxdb"  # InfluxDB data
      - "C:/navod/Academic/sem7/fyp/chronograf:/root/"  # Chronograf data