aliases: []
creation_timestamp: 1746014271719
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1746014271719
metrics: null
model_id: ''
name: detr-resnet-50-panoptic
params: null
run_id: af0d43d8f1564fe3ba062df8178ee633
run_link: ''
source: mlflow-artifacts:/153182651116884391/af0d43d8f1564fe3ba062df8178ee633/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/153182651116884391/af0d43d8f1564fe3ba062df8178ee633/artifacts/model
user_id: null
version: 1
