aliases: []
creation_timestamp: 1745996061795
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1745996061795
metrics: null
model_id: ''
name: donut-base-finetuned-docvqa
params: null
run_id: f9b0866ef2d54d11b4ada403a73e6927
run_link: ''
source: mlflow-artifacts:/507893471775702031/f9b0866ef2d54d11b4ada403a73e6927/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/507893471775702031/f9b0866ef2d54d11b4ada403a73e6927/artifacts/model
user_id: null
version: 3
