aliases: []
creation_timestamp: 1745994132498
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1745994132498
metrics: null
model_id: ''
name: donut-base-finetuned-docvqa
params: null
run_id: 8806d4e6ec304e89b517a21c84e8b090
run_link: ''
source: mlflow-artifacts:/507893471775702031/8806d4e6ec304e89b517a21c84e8b090/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/507893471775702031/8806d4e6ec304e89b517a21c84e8b090/artifacts/model
user_id: null
version: 2
