aliases: []
creation_timestamp: 1746006490896
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1746006490896
metrics: null
model_id: ''
name: Intel-dpt-large
params: null
run_id: 4b75fcfacd214ab19eca19a06a3ef542
run_link: ''
source: mlflow-artifacts:/880837473876409857/4b75fcfacd214ab19eca19a06a3ef542/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/880837473876409857/4b75fcfacd214ab19eca19a06a3ef542/artifacts/model
user_id: null
version: 2
