aliases: []
creation_timestamp: 1744288590314
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1744288590314
metrics: null
model_id: ''
name: CustomerChurn1
params: null
run_id: 2fcd4f40413f43749b510a76aaf7718a
run_link: ''
source: mlflow-artifacts:/604546765226410249/2fcd4f40413f43749b510a76aaf7718a/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/604546765226410249/2fcd4f40413f43749b510a76aaf7718a/artifacts/model
user_id: null
version: 1
