aliases: []
creation_timestamp: 1745997999407
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1745997999407
metrics: null
model_id: ''
name: multilingual-sentiment-analysis
params: null
run_id: 4db8577dee044975af78c0b962728010
run_link: ''
source: mlflow-artifacts:/262403900183639743/4db8577dee044975af78c0b962728010/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/262403900183639743/4db8577dee044975af78c0b962728010/artifacts/model
user_id: null
version: 2
