aliases: []
creation_timestamp: 1745993945832
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1745993945832
metrics: null
model_id: ''
name: donut-base-finetuned-docvqa
params: null
run_id: 639bdc47b9b843d49b26b7b6e41a7650
run_link: ''
source: mlflow-artifacts:/507893471775702031/639bdc47b9b843d49b26b7b6e41a7650/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/507893471775702031/639bdc47b9b843d49b26b7b6e41a7650/artifacts/model
user_id: null
version: 1
