aliases: []
creation_timestamp: 1747740019848
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1747740019848
metrics: null
model_id: ''
name: donut-base-finetuned-docvqa
params: null
run_id: 359552edb63e48aa8cf89251ec1c6716
run_link: ''
source: mlflow-artifacts:/299964540032896922/359552edb63e48aa8cf89251ec1c6716/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/299964540032896922/359552edb63e48aa8cf89251ec1c6716/artifacts/model
user_id: null
version: 1
