aliases: []
creation_timestamp: 1746012089355
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1746012089355
metrics: null
model_id: ''
name: detr-resnet-50
params: null
run_id: dab66d6db27a475582421bee9c02db94
run_link: ''
source: mlflow-artifacts:/944600681884899737/dab66d6db27a475582421bee9c02db94/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/944600681884899737/dab66d6db27a475582421bee9c02db94/artifacts/model
user_id: null
version: 1
