aliases: []
creation_timestamp: 1745997743817
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1745997743817
metrics: null
model_id: ''
name: multilingual-sentiment-analysis
params: null
run_id: 9dd50c9fdc3f40ee9dd85edd91242b90
run_link: ''
source: mlflow-artifacts:/262403900183639743/9dd50c9fdc3f40ee9dd85edd91242b90/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/262403900183639743/9dd50c9fdc3f40ee9dd85edd91242b90/artifacts/model
user_id: null
version: 1
