aliases: []
creation_timestamp: 1747740498278
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1747740498278
metrics: null
model_id: ''
name: Intel-dpt-large
params: null
run_id: 717bc903c0cf464aa7dac327d1c77d92
run_link: ''
source: mlflow-artifacts:/162470636026093514/717bc903c0cf464aa7dac327d1c77d92/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/162470636026093514/717bc903c0cf464aa7dac327d1c77d92/artifacts/model
user_id: null
version: 1
