aliases: []
creation_timestamp: 1746001521593
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1746001521593
metrics: null
model_id: ''
name: Intel-dpt-large
params: null
run_id: 68894cb531414ff59a2b1bfa0889692c
run_link: ''
source: mlflow-artifacts:/880837473876409857/68894cb531414ff59a2b1bfa0889692c/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/880837473876409857/68894cb531414ff59a2b1bfa0889692c/artifacts/model
user_id: null
version: 1
